# Compare GPU Roofline Results

This notebook reloads and re-parses Nsight Compute report files for multiple GPUs, normalizes the data, and compares per-kernel roofline metrics (traffic, FLOPs, arithmetic intensity, and timing) across devices for both CUDA and OpenMP builds.

In [12]:
import pandas as pd
import os
import glob
import numpy as np
import seaborn as sns
import json
import matplotlib.pyplot as plt
import re
import sys
from tqdm import tqdm

sys.path.append('../')
from utils import *
from gatherData import _parse_ncu_report, roofline_results_to_df, calc_roofline_data 

from tqdm.contrib.concurrent import process_map
from functools import partial
import os
from os import path


from sass_helper import *

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)

In [13]:
# kernel key and metrics
key_cols = ['source', 'Kernel Name', 'exeArgs', 'Block Size', 'Grid Size', 'model_type']
device_col = 'device'

groupings = key_cols + [device_col]
metrics = ['SP_FLOP', 'DP_FLOP', 'HP_FLOP', 'INTOP', 'traffic',
           'bytesRead', 'bytesWrite', 'bytesTotal',
           'dpAI', 'spAI', 'hpAI',
           'dpPerf', 'spPerf', 'hpPerf', 'xtime']

log_metrics = ['traffic', 'xtime']

# all cols
all_cols = groupings + metrics + ['sample']

# markers we should ignore / drop kernels containing these from the dataset
#library_markers = [ 'cub::', 'thrust::', '__cuda_' ]

In [14]:
df = pd.read_csv('all-NCU-GPU-Data.csv', low_memory=False)
print(df.shape)
print(df.columns)


# let's rename the device column
def rename_devices(x):
    if '3080' in x:
        return '3080'
    elif 'A100' in x:
        return 'A100'
    elif 'A10' in x:
        return 'A10'
    elif 'H100' in x:
        return 'H100'
    else:
        raise ValueError(f'Unknown device name in {x}')

df['device'] = df['device'].apply(lambda x: rename_devices(x))

(20044, 2659)
Index(['ID', 'Process ID', 'Process Name', 'Host Name', 'Kernel Name',
       'Context', 'Stream', 'Block Size', 'Grid Size', 'Device',
       ...
       'smsp__sass_inst_executed_op_shared.sum.pct_of_peak_sustained_elapsed',
       'smsp__sass_inst_executed_op_shared_gmma.sum',
       'smsp__sass_inst_executed_op_shared_gmma.sum.pct_of_peak_sustained_elapsed',
       'smsp__sass_inst_executed_op_tma_ld.sum',
       'smsp__sass_inst_executed_op_tma_red.sum',
       'smsp__sass_inst_executed_op_tma_st.sum', 'launch_cluster_dim_x',
       'launch_cluster_dim_z', 'launch_cluster_max_active',
       'launch_cluster_dim_y'],
      dtype='object', length=2659)

In [15]:
display(df[all_cols].head(10))

,source,Kernel Name,exeArgs,Block Size,Grid Size,model_type,device,SP_FLOP,DP_FLOP,HP_FLOP,INTOP,traffic,bytesRead,bytesWrite,bytesTotal,dpAI,spAI,hpAI,dpPerf,spPerf,hpPerf,xtime,sample
0,accuracy-cuda,_Z15accuracy_kerneliiiPKfPKiPi,8192 10000 10 100,"(256, 1, 1)","(2048, 1, 1)",cuda,3080,0,0,0,5.629983e+08,6.449159e+11,327800576,1797888,329598464,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,511072.0,1
1,accuracy-cuda,_Z15accuracy_kerneliiiPKfPKiPi,8192 10000 10 100,"(256, 1, 1)","(2048, 1, 1)",cuda,3080,0,0,0,5.629983e+08,6.425681e+11,327824384,1766784,329591168,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,512928.0,2
2,accuracy-cuda,_Z15accuracy_kerneliiiPKfPKiPi,8192 10000 10 100,"(256, 1, 1)","(2048, 1, 1)",cuda,3080,0,0,0,5.629983e+08,6.443553e+11,327800320,1800320,329600640,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,511520.0,3
3,accuracy-omp,__omp_offloading_10305_2b800b0_main_l57,8192 10000 10 100,"(128, 1, 1)","(2048, 1, 1)",omp,3080,0,0,0,1.003935e+09,5.279006e+11,327974528,1756416,329730944,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,624608.0,1
4,accuracy-omp,__omp_offloading_10305_2b800b0_main_l57,8192 10000 10 100,"(128, 1, 1)","(2048, 1, 1)",omp,3080,0,0,0,1.003935e+09,5.271992e+11,327968896,1762560,329731456,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,625440.0,2
5,accuracy-omp,__omp_offloading_10305_2b800b0_main_l57,8192 10000 10 100,"(128, 1, 1)","(2048, 1, 1)",omp,3080,0,0,0,1.003935e+09,5.287411e+11,327975808,1772544,329748352,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,623648.0,3
6,ace-cuda,_Z14calculateForcePA400_A400_dS1_S1_S1_dddddd,100,"(8, 8, 4)","(50, 50, 100)",cuda,3080,378175731,7817840356,0,7.015186e+09,6.507823e+10,764802432,1538377728,2303180160,3.394368,0.164197,0.0,2.208995e+11,1.068566e+10,0.0,35390944.0,1
7,ace-cuda,_Z9allenCahnPA400_A400_dS1_S1_S1_S1_S1_dddddddd,100,"(8, 8, 4)","(50, 50, 100)",cuda,3080,882719027,14814682409,0,1.476101e+10,6.287344e+10,3050602496,508060544,3558663040,4.162991,0.248048,0.0,2.617416e+11,1.559563e+10,0.0,56600416.0,1
8,ace-cuda,_Z21boundaryConditionsPhiPA400_A400_d,100,"(8, 8, 4)","(50, 50, 100)",cuda,3080,0,0,0,1.084807e+09,5.832238e+10,19200,15426432,15445632,0.000000,0.000000,0.0,0.000000e+00,0.000000e+00,0.0,264832.0,1
9,ace-cuda,_Z15thermalEquationPA400_A400_dS1_S1_S1_ddddd,100,"(8, 8, 4)","(50, 50, 100)",cuda,3080,378358346,7173243211,0,6.858070e+09,8.250915e+10,1779667968,507345664,2287013632,3.136511,0.165438,0.0,2.587908e+11,1.365013e+10,0.0,27718304.0,1

In [16]:
sass = pd.read_csv('imix_data.csv', low_memory=False)
print(sass.shape)
print(sass.columns)
print(sass.columns[68], sass.columns[74])

(14757, 151)
Index(['Kernel Name', 'Program', 'Model', 'SM', 'Num Labels', 'Num References',
       'Num Self References', 'Num Circular Dependencies', 'Num Predicated',
       'Num Lines',
       ...
       'TEX', 'BRXU', 'I2FP', 'F2IP', 'VIADD', 'VIADDMNMX', 'ENDCOLLECTIVE',
       'VIMNMX', 'CGAERRBAR', 'VIMNMX3'],
      dtype='object', length=151)
SEL UIADD3

In [17]:
display(sass.head(10))

,Kernel Name,Program,Model,SM,Num Labels,Num References,Num Self References,Num Circular Dependencies,Num Predicated,Num Lines,Num Constant Math,Num FP16,Num FP32,Num FP64,Num Global Loads,Num Global Stores,Labels,References,OpType_movement,OpType_integer,OpType_synchronization,OpType_control,OpType_floating point,MOV,LOP3,...,UP2UR,UPRMT,USGXT,NANOSLEEP,BREV,UPLOP3,B2R,BMSK,HMMA,HSET2,VABSDIFF4,UBREV,MATCH,OpType_texture,AddrSpace_texture,TEX,BRXU,I2FP,F2IP,VIADD,VIADDMNMX,ENDCOLLECTIVE,VIMNMX,CGAERRBAR,VIMNMX3
0,__cuda_sm20_sqrt_rn_f32_slowpath,vmc,cuda,sm_80,4,0,0,0,15,32,5,0,12,0,0,0,".L_x_10,.L_x_9,.L_x_11,.L_x_59",NaN,4.0,1.0,2.0,13,12.0,4.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,_Z9propagateiiPfS_S_S_S_S_S_S_Pj,vmc,cuda,sm_80,33,6,0,0,9,264,112,4,86,0,12,12,".L_x_36,.L_x_0,.L_x_15,.L_x_16,.L_x_14,.L_x_1,...","__cuda_sm20_sqrt_rn_f32_slowpath,__cuda_sm20_s...",25.0,59.0,16.0,40,90.0,49.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,_Z10initializePfS_S_S_S_S_S_Pj,vmc,cuda,sm_80,14,3,0,0,3,136,70,4,50,0,1,8,".L_x_6,.L_x_39,.L_x_40,.L_x_38,.L_x_7,.L_x_42,...","__cuda_sm20_sqrt_rn_f32_slowpath,__cuda_sm20_s...",11.0,28.0,6.0,19,54.0,23.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,_Z10zero_statsiPf,vmc,cuda,sm_80,2,0,0,0,0,32,8,1,0,0,0,4,".L_x_48,.L_x_62",NaN,2.0,7.0,0.0,15,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,_Z7initranjPj,vmc,cuda,sm_80,2,0,0,0,0,24,6,1,0,0,0,1,".L_x_49,.L_x_63",NaN,2.0,5.0,0.0,12,1.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,_Z15SumWithinBlocksiPKfPf,vmc,cuda,sm_80,8,0,0,0,42,152,65,4,14,0,5,1,".L_x_54,.L_x_53,.L_x_52,.L_x_55,.L_x_51,.L_x_5...",NaN,3.0,64.0,13.0,17,18.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,_Z15LCG_random_initPj,vmc,cuda,sm_80,2,0,0,0,0,16,3,1,0,0,0,0,".L_x_57,.L_x_65",NaN,0.0,2.0,0.0,10,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,_Z10LCG_randomPj,vmc,cuda,sm_80,2,0,0,0,0,24,4,1,1,0,0,0,".L_x_58,.L_x_66",NaN,2.0,2.0,0.0,14,2.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,__kmpc_get_hardware_thread_id_in_block,sort,omp,sm_80,2,0,0,0,0,16,0,0,0,0,0,0,".L_x_4,.L_x_40",NaN,0.0,0.0,0.0,15,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,__omp_offloading_fd01_183cbd_main_l146,sort,omp,sm_80,16,1,0,0,35,304,118,2,1,0,5,4,".L_x_0,.L_x_17,.L_x_7,.L_x_6,.L_x_12,.L_x_9,.L...",__kmpc_get_hardware_thread_id_in_block,8.0,122.0,27.0,28,3.0,4.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# need to rename some of the columns and make a few new ones to match the NCU data
# some of the rows in the imix data will not appear in the perf counter data, as some functions are __device__ functions that are inlined or called by the __global__ kernels

sass['source'] = sass['Program'] + '-' + sass['Model']

In [19]:
# let's add an sm_arch column to the df

device_to_sm_arch = {
    '3080': 'sm_86',
    'A100': 'sm_80',
    'A10': 'sm_86',
    'H100': 'sm_90'
}   

df['SM'] = df['device'].apply(lambda x: device_to_sm_arch[x])

print(df.shape)

(20044, 2660)

In [20]:

def fix_omp_kernel_name(x):
    if '__omp_offloading' in x:
        # we need to do a regex here to extract the function name after the following 
        # possible string patterns:
        # __omp_offloading_fd01_2c7d38_
        # __omp_offloading_10305_2b800c7_
        match = re.search(r'__omp_offloading_.*?_.*?_(.+)$', x)
        if match:
            return match.group(1)
    return x

df['Kernel Name'] = df['Kernel Name'].apply(lambda x: fix_omp_kernel_name(x))   
sass['Kernel Name'] = sass['Kernel Name'].apply(lambda x: fix_omp_kernel_name(x))

In [21]:
# let's match up the 'source', 'Kernel Name', and 'SM' columns in the perf counter data with the 'source', 'Kernel Name', and 'SM' columns in the imix data, and add the imix metrics to the perf counter dataframe

df_merged = pd.merge(df, sass, on=['source', 'Kernel Name', 'SM'], how='left', suffixes=('', '_sass'))

In [22]:
print(df_merged.shape)
print(df_merged.columns)
print(len(df_merged.columns))

(21121, 2809)
Index(['ID', 'Process ID', 'Process Name', 'Host Name', 'Kernel Name',
       'Context', 'Stream', 'Block Size', 'Grid Size', 'Device',
       ...
       'TEX', 'BRXU', 'I2FP', 'F2IP', 'VIADD', 'VIADDMNMX', 'ENDCOLLECTIVE',
       'VIMNMX', 'CGAERRBAR', 'VIMNMX3'],
      dtype='object', length=2809)
2809

In [23]:

display(df_merged.head(15))

,ID,Process ID,Process Name,Host Name,Kernel Name,Context,Stream,Block Size,Grid Size,Device,CC,FBSP.TriageSCG.dramc__read_throughput.avg.pct_of_peak_sustained_elapsed,FBSP.TriageSCG.dramc__throughput.avg.pct_of_peak_sustained_elapsed,FBSP.TriageSCG.dramc__write_throughput.avg.pct_of_peak_sustained_elapsed,FE_B.TriageAC.gr__ctas_launched_queue_sync.sum,LTS.TriageSCG.lts__average_t_sector_hit_rate_realtime.pct,LTS.TriageSCG.lts__throughput.avg.pct_of_peak_sustained_elapsed,SM_A.TriageAC.l1tex__data_pipe_lsu_wavefronts.avg,SM_A.TriageAC.l1tex__lsu_writeback_active.avg,SM_A.TriageAC.sm__cycles_active.avg,SM_A.TriageAC.sm__inst_executed_realtime.avg.per_cycle_active,SM_A.TriageSCG.l1tex__throughput.avg.pct_of_peak_sustained_elapsed,SM_A.TriageSCG.sm__inst_executed_pipe_alu_realtime.avg.pct_of_peak_sustained_elapsed,SM_B.TriageAC.l1tex__t_sector_hit_rate.pct,SM_C.TriageSCG.smsp__inst_executed_pipe_fmaheavy.avg.pct_of_peak_sustained_elapsed,...,UP2UR,UPRMT,USGXT,NANOSLEEP,BREV,UPLOP3,B2R,BMSK,HMMA,HSET2,VABSDIFF4,UBREV,MATCH,OpType_texture,AddrSpace_texture,TEX,BRXU,I2FP,F2IP,VIADD,VIADDMNMX,ENDCOLLECTIVE,VIMNMX,CGAERRBAR,VIMNMX3
0,0.0,566100.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"44,338.63","42,483.88","686,209.49",319.61,NaN,12.29,NaN,6.14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,566220.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"44,340.56","42,483.90","687,543.22",318.42,NaN,12.26,NaN,6.12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,566354.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"44,344.29","42,483.88","686,880.26",319.07,NaN,12.17,NaN,6.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,566433.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"56,740.00","46,188.44","861,213.01",640.42,NaN,17.64,NaN,5.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,566547.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"56,740.71","46,188.41","860,023.71",641.49,NaN,20.88,NaN,6.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,566656.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,NaN,NaN,NaN,"2,048",NaN,NaN,"56,740.10","46,188.40","859,528.90",641.50,NaN,18.77,NaN,5.68,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,566735.0,ace,127.0.0.1,_Z14calculateForcePA400_A400_dS1_S1_S1_dddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"1,365,062.16","669,550.59","50,960,093.99",910.45,NaN,3.62,NaN,1.49,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1.0,566735.0,ace,127.0.0.1,_Z9allenCahnPA400_A400_dS1_S1_S1_S1_S1_dddddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"2,016,748.40","1,403,644.34","81,489,728.04",817.06,NaN,4.64,NaN,1.86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2.0,566735.0,ace,127.0.0.1,_Z21boundaryConditionsPhiPA400_A400_d,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"94,067.76","88,235.29","378,540.38",700.25,NaN,32.81,NaN,21.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3.0,566735.0,ace,127.0.0.1,_Z15thermalEquationPA400_A400_dS1_S1_S1_ddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"1,490,067.35","1,035,440.25","39,900,826.66",804.24,NaN,4.50,NaN,1.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,4.0,566735.0,ace,127.0.0.1,_Z19boundaryConditionsUPA400_A400_dd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"94,067.76","88,235.29","388,116.99",699.11,NaN,27.63,NaN,18.42,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,5.0,566735.0,ace,127.0.0.1,_Z8swapGridPA400_A400_dS1_,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"581,970.19","268,145.03","4,826,779.12",276.57,NaN,1.42,NaN,2.56,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,567115.0,ace,127.0.0.1,_Z14calculateForcePA400_A400_dS1_S1_S1_dddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"1,365,195.22","669,511.25","50,955,650.15",910.12,NaN,3.61,NaN,1.48,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1.0,567115.0,ace,127.0.0.1,_Z9allenCahnPA400_A400_dS1_S1_S1_S1_S1_dddddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"2,016,888.13","1,403,510.54","81,491,311.29",817.04,NaN,4.65,NaN,1.86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2.0,567115.0,ace,127.0.0.1,_Z21boundaryConditionsPhiPA400_A400_d,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,NaN,NaN,NaN,"250,000",NaN,NaN,"94,067.76","88,235.29","379,277.81",700.45,NaN,30.45,NaN,20.11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:

subset = sass[(sass['Kernel Name'] == '_Z12geglu_kernelIffLi160ELi1280ELi8ELi2EEvPT_PKS0_') & 
              (sass['SM'] == 'sm_90')]

display(subset)

,Kernel Name,Program,Model,SM,Num Labels,Num References,Num Self References,Num Circular Dependencies,Num Predicated,Num Lines,Num Constant Math,Num FP16,Num FP32,Num FP64,Num Global Loads,Num Global Stores,Labels,References,OpType_movement,OpType_integer,OpType_synchronization,OpType_control,OpType_floating point,MOV,LOP3,...,UPRMT,USGXT,NANOSLEEP,BREV,UPLOP3,B2R,BMSK,HMMA,HSET2,VABSDIFF4,UBREV,MATCH,OpType_texture,AddrSpace_texture,TEX,BRXU,I2FP,F2IP,VIADD,VIADDMNMX,ENDCOLLECTIVE,VIMNMX,CGAERRBAR,VIMNMX3,source
10901,_Z12geglu_kernelIffLi160ELi1280ELi8ELi2EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,48,472,407,6,400,0,8,4,".L_x_2,.L_x_8",NaN,5.0,26.0,0.0,17,406.0,5.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda

In [27]:

subset = sass[(sass['source'] == 'geglu-cuda') & 
              (sass['SM'] == 'sm_90')]

display(subset)

,Kernel Name,Program,Model,SM,Num Labels,Num References,Num Self References,Num Circular Dependencies,Num Predicated,Num Lines,Num Constant Math,Num FP16,Num FP32,Num FP64,Num Global Loads,Num Global Stores,Labels,References,OpType_movement,OpType_integer,OpType_synchronization,OpType_control,OpType_floating point,MOV,LOP3,...,UPRMT,USGXT,NANOSLEEP,BREV,UPLOP3,B2R,BMSK,HMMA,HSET2,VABSDIFF4,UBREV,MATCH,OpType_texture,AddrSpace_texture,TEX,BRXU,I2FP,F2IP,VIADD,VIADDMNMX,ENDCOLLECTIVE,VIMNMX,CGAERRBAR,VIMNMX3,source
10899,_Z12geglu_kernelIffLi160ELi5120ELi8ELi2EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,48,480,436,4,400,0,8,4,".L_x_0,.L_x_6",NaN,3.0,40.0,0.0,15,404.0,3.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda
10900,_Z12geglu_kernelIffLi160ELi2560ELi8ELi2EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,48,472,432,4,400,0,8,4,".L_x_1,.L_x_7",NaN,3.0,37.0,0.0,10,404.0,3.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda
10901,_Z12geglu_kernelIffLi160ELi1280ELi8ELi2EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,48,472,407,6,400,0,8,4,".L_x_2,.L_x_8",NaN,5.0,26.0,0.0,17,406.0,5.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda
10902,_Z12geglu_kernelIffLi160ELi5120ELi8ELi1EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,24,256,211,5,200,0,4,2,".L_x_3,.L_x_9",NaN,4.0,20.0,0.0,15,205.0,4.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda
10903,_Z12geglu_kernelIffLi160ELi2560ELi8ELi1EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,24,256,211,5,200,0,4,2,".L_x_4,.L_x_10",NaN,4.0,20.0,0.0,15,205.0,4.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda
10904,_Z12geglu_kernelIffLi160ELi1280ELi8ELi1EEvPT_P...,geglu,cuda,sm_90,2,0,0,0,24,248,208,5,200,0,4,2,".L_x_5,.L_x_11",NaN,4.0,17.0,0.0,10,205.0,4.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,geglu-cuda

In [29]:
print(df_merged.shape)

print(df_merged.head(10))

(21121, 2809)
    ID  Process ID Process Name  Host Name  \
0  0.0    566100.0     accuracy  127.0.0.1
1  0.0    566220.0     accuracy  127.0.0.1
2  0.0    566354.0     accuracy  127.0.0.1
3  0.0    566433.0     accuracy  127.0.0.1
4  0.0    566547.0     accuracy  127.0.0.1
5  0.0    566656.0     accuracy  127.0.0.1
6  0.0    566735.0          ace  127.0.0.1
7  1.0    566735.0          ace  127.0.0.1
8  2.0    566735.0          ace  127.0.0.1
9  3.0    566735.0          ace  127.0.0.1

                                       Kernel Name  Context  Stream  \
0                   _Z15accuracy_kerneliiiPKfPKiPi      1.0     7.0
1                   _Z15accuracy_kerneliiiPKfPKiPi      1.0     7.0
2                   _Z15accuracy_kerneliiiPKfPKiPi      1.0     7.0
3                                         main_l57      1.0    13.0
4                                         main_l57      1.0    13.0
5                                         main_l57      1.0    13.0
6    _Z14calculateForcePA400_A400_dS1_S1_S1_dddddd      1.0     7.0
7  _Z9allenCahnPA400_A400_dS1_S1_S1_S1_S1_dddddddd      1.0     7.0
8            _Z21boundaryConditionsPhiPA400_A400_d      1.0     7.0
9    _Z15thermalEquationPA400_A400_dS1_S1_S1_ddddd      1.0     7.0

    Block Size      Grid Size  Device   CC  \
0  (256, 1, 1)   (2048, 1, 1)     0.0  8.6
1  (256, 1, 1)   (2048, 1, 1)     0.0  8.6
2  (256, 1, 1)   (2048, 1, 1)     0.0  8.6
3  (128, 1, 1)   (2048, 1, 1)     0.0  8.6
4  (128, 1, 1)   (2048, 1, 1)     0.0  8.6
5  (128, 1, 1)   (2048, 1, 1)     0.0  8.6
6    (8, 8, 4)  (50, 50, 100)     0.0  8.6
7    (8, 8, 4)  (50, 50, 100)     0.0  8.6
8    (8, 8, 4)  (50, 50, 100)     0.0  8.6
9    (8, 8, 4)  (50, 50, 100)     0.0  8.6

   FBSP.TriageSCG.dramc__read_throughput.avg.pct_of_peak_sustained_elapsed  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

   FBSP.TriageSCG.dramc__throughput.avg.pct_of_peak_sustained_elapsed  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

   FBSP.TriageSCG.dramc__write_throughput.avg.pct_of_peak_sustained_elapsed  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

  FE_B.TriageAC.gr__ctas_launched_queue_sync.sum  \
0                                          2,048
1                                          2,048
2                                          2,048
3                                          2,048
4                                          2,048
5                                          2,048
6                                        250,000
7                                        250,000
8                                        250,000
9                                        250,000

   LTS.TriageSCG.lts__average_t_sector_hit_rate_realtime.pct  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

   LTS.TriageSCG.lts__throughput.avg.pct_of_peak_sustained_elapsed  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

  SM_A.TriageAC.l1tex__data_pipe_lsu_wavefronts.avg  \
0                                         44,338.63
1                                         44,340.56
2                                         44,344.29
3                                         56,740.00
4                                         56,740.71
5                                         56,740.10
6                                      1,365,062.16
7                                      2,016,748.40
8                                         94,067.76
9                                      1,490,067.35

  SM_A.TriageAC.l1tex__lsu_writeback_active.avg  \
0                                     42,483.88
1                                     42,483.90
2                                     42,483.88
3                                     46,188.44
4                                     46,188.41
5                                     46,188.40
6                                    669,550.59
7                                  1,403,644.34
8                                     88,235.29
9                                  1,035,440.25

  SM_A.TriageAC.sm__cycles_active.avg  \
0                          686,209.49
1                          687,543.22
2                          686,880.26
3                          861,213.01
4                          860,023.71
5                          859,528.90
6                       50,960,093.99
7                       81,489,728.04
8                          378,540.38
9                       39,900,826.66

  SM_A.TriageAC.sm__inst_executed_realtime.avg.per_cycle_active  \
0                                             319.61
1                                             318.42
2                                             319.07
3                                             640.42
4                                             641.49
5                                             641.50
6                                             910.45
7                                             817.06
8                                             700.25
9                                             804.24

   SM_A.TriageSCG.l1tex__throughput.avg.pct_of_peak_sustained_elapsed  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

   SM_A.TriageSCG.sm__inst_executed_pipe_alu_realtime.avg.pct_of_peak_sustained_elapsed  \
0                                              12.29
1                                              12.26
2                                              12.17
3                                              17.64
4                                              20.88
5                                              18.77
6                                               3.62
7                                               4.64
8                                              32.81
9                                               4.50

   SM_B.TriageAC.l1tex__t_sector_hit_rate.pct  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN

   SM_C.TriageSCG.smsp__inst_executed_pipe_fmaheavy.avg.pct_of_peak_sustained_elapsed  \
0                                               6.14
1                                               6.12
2                                               6.07
3                                               5.34
4                                               6.32
5                                               5.68
6                                               1.49
7                                               1.86
8                                              21.66
9                                               1.89

   ...  UP2UR UPRMT USGXT  NANOSLEEP  BREV UPLOP3  B2R BMSK HMMA HSET2  \
0  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
1  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
2  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
3  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
4  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
5  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
6  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
7  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
8  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0
9  ...    0.0   0.0   0.0        0.0   0.0    0.0  0.0  0.0  0.0   0.0

  VABSDIFF4 UBREV  MATCH OpType_texture AddrSpace_texture  TEX BRXU I2FP F2IP  \
0       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
1       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
2       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
3       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
4       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
5       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
6       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
7       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
8       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0
9       0.0   0.0    0.0            0.0               0.0  0.0  0.0  0.0  0.0

  VIADD VIADDMNMX ENDCOLLECTIVE VIMNMX CGAERRBAR  VIMNMX3
0   0.0       0.0           0.0    0.0       0.0      0.0
1   0.0       0.0           0.0    0.0       0.0      0.0
2   0.0       0.0           0.0    0.0       0.0      0.0
3   0.0       0.0           0.0    0.0       0.0      0.0
4   0.0       0.0           0.0    0.0       0.0      0.0
5   0.0       0.0           0.0    0.0       0.0      0.0
6   0.0       0.0           0.0    0.0       0.0      0.0
7   0.0       0.0           0.0    0.0       0.0      0.0
8   0.0       0.0           0.0    0.0       0.0      0.0
9   0.0       0.0           0.0    0.0       0.0      0.0

[10 rows x 2809 columns]

In [ ]:
# let's replace the NaN values with -1, since these represent performance counter values that were not gathered.

df_merged.fillna(-1, inplace=True)

df_merged.to_csv('all-NCU-GPU-Data-with-IMIX.csv', index=False)

,ID,Process ID,Process Name,Host Name,Kernel Name,Context,Stream,Block Size,Grid Size,Device,CC,FBSP.TriageSCG.dramc__read_throughput.avg.pct_of_peak_sustained_elapsed,FBSP.TriageSCG.dramc__throughput.avg.pct_of_peak_sustained_elapsed,FBSP.TriageSCG.dramc__write_throughput.avg.pct_of_peak_sustained_elapsed,FE_B.TriageAC.gr__ctas_launched_queue_sync.sum,LTS.TriageSCG.lts__average_t_sector_hit_rate_realtime.pct,LTS.TriageSCG.lts__throughput.avg.pct_of_peak_sustained_elapsed,SM_A.TriageAC.l1tex__data_pipe_lsu_wavefronts.avg,SM_A.TriageAC.l1tex__lsu_writeback_active.avg,SM_A.TriageAC.sm__cycles_active.avg,SM_A.TriageAC.sm__inst_executed_realtime.avg.per_cycle_active,SM_A.TriageSCG.l1tex__throughput.avg.pct_of_peak_sustained_elapsed,SM_A.TriageSCG.sm__inst_executed_pipe_alu_realtime.avg.pct_of_peak_sustained_elapsed,SM_B.TriageAC.l1tex__t_sector_hit_rate.pct,SM_C.TriageSCG.smsp__inst_executed_pipe_fmaheavy.avg.pct_of_peak_sustained_elapsed,...,UP2UR,UPRMT,USGXT,NANOSLEEP,BREV,UPLOP3,B2R,BMSK,HMMA,HSET2,VABSDIFF4,UBREV,MATCH,OpType_texture,AddrSpace_texture,TEX,BRXU,I2FP,F2IP,VIADD,VIADDMNMX,ENDCOLLECTIVE,VIMNMX,CGAERRBAR,VIMNMX3
0,0.0,566100.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"44,338.63","42,483.88","686,209.49",319.61,-1.0,12.29,-1.0,6.14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,566220.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"44,340.56","42,483.90","687,543.22",318.42,-1.0,12.26,-1.0,6.12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,566354.0,accuracy,127.0.0.1,_Z15accuracy_kerneliiiPKfPKiPi,1.0,7.0,"(256, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"44,344.29","42,483.88","686,880.26",319.07,-1.0,12.17,-1.0,6.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,566433.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"56,740.00","46,188.44","861,213.01",640.42,-1.0,17.64,-1.0,5.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,566547.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"56,740.71","46,188.41","860,023.71",641.49,-1.0,20.88,-1.0,6.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,566656.0,accuracy,127.0.0.1,main_l57,1.0,13.0,"(128, 1, 1)","(2048, 1, 1)",0.0,8.6,-1.0,-1.0,-1.0,"2,048",-1.0,-1.0,"56,740.10","46,188.40","859,528.90",641.50,-1.0,18.77,-1.0,5.68,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,566735.0,ace,127.0.0.1,_Z14calculateForcePA400_A400_dS1_S1_S1_dddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,-1.0,-1.0,-1.0,"250,000",-1.0,-1.0,"1,365,062.16","669,550.59","50,960,093.99",910.45,-1.0,3.62,-1.0,1.49,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1.0,566735.0,ace,127.0.0.1,_Z9allenCahnPA400_A400_dS1_S1_S1_S1_S1_dddddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,-1.0,-1.0,-1.0,"250,000",-1.0,-1.0,"2,016,748.40","1,403,644.34","81,489,728.04",817.06,-1.0,4.64,-1.0,1.86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2.0,566735.0,ace,127.0.0.1,_Z21boundaryConditionsPhiPA400_A400_d,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,-1.0,-1.0,-1.0,"250,000",-1.0,-1.0,"94,067.76","88,235.29","378,540.38",700.25,-1.0,32.81,-1.0,21.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3.0,566735.0,ace,127.0.0.1,_Z15thermalEquationPA400_A400_dS1_S1_S1_ddddd,1.0,7.0,"(8, 8, 4)","(50, 50, 100)",0.0,8.6,-1.0,-1.0,-1.0,"250,000",-1.0,-1.0,"1,490,067.35","1,035,440.25","39,900,826.66",804.24,-1.0,4.50,-1.0,1.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
for col in df_merged.columns:
    print(col)

ID
Process ID
Process Name
Host Name
Kernel Name
Context
Stream
Block Size
Grid Size
Device
CC
FBSP.TriageSCG.dramc__read_throughput.avg.pct_of_peak_sustained_elapsed
FBSP.TriageSCG.dramc__throughput.avg.pct_of_peak_sustained_elapsed
FBSP.TriageSCG.dramc__write_throughput.avg.pct_of_peak_sustained_elapsed
FE_B.TriageAC.gr__ctas_launched_queue_sync.sum
LTS.TriageSCG.lts__average_t_sector_hit_rate_realtime.pct
LTS.TriageSCG.lts__throughput.avg.pct_of_peak_sustained_elapsed
SM_A.TriageAC.l1tex__data_pipe_lsu_wavefronts.avg
SM_A.TriageAC.l1tex__lsu_writeback_active.avg
SM_A.TriageAC.sm__cycles_active.avg
SM_A.TriageAC.sm__inst_executed_realtime.avg.per_cycle_active
SM_A.TriageSCG.l1tex__throughput.avg.pct_of_peak_sustained_elapsed
SM_A.TriageSCG.sm__inst_executed_pipe_alu_realtime.avg.pct_of_peak_sustained_elapsed
SM_B.TriageAC.l1tex__t_sector_hit_rate.pct
SM_C.TriageSCG.smsp__inst_executed_pipe_fmaheavy.avg.pct_of_peak_sustained_elapsed
SM_C.TriageSCG.smsp__inst_executed_pipe_fmalite.avg.pct_of_peak_sustained_elapsed
TriageAC.tpc__warps_active_realtime.avg.per_cycle_active
TriageAC.tpc__warps_active_realtime.sum.per_cycle_active
c2clink__enabled_mask
c2clink__present
derived__avg_thread_executed
derived__avg_thread_executed_true
derived__avg_thread_unexecuted_true
derived__derivative_avg_thread_executed_true
derived__l1tex__lsu_writeback_bytes_mem_lg.sum.peak_sustained
derived__l1tex__lsu_writeback_bytes_mem_lg.sum.per_second
derived__local_spilling_requests
derived__local_spilling_requests_pct
derived__lts__lts2xbar_bytes.sum.peak_sustained
derived__lts__lts2xbar_bytes.sum.per_second
derived__memory_l1_conflicts_shared_nway
derived__memory_l1_wavefronts_shared_excessive
derived__memory_l2_theoretical_sectors_global_excessive
derived__pct_occupancy_per_block_size
derived__pct_occupancy_per_register_count
derived__pct_occupancy_per_shared_mem_size
derived__sm__sass_thread_inst_executed_op_dfma_pred_on_x2
derived__sm__sass_thread_inst_executed_op_ffma_pred_on_x2
derived__sm__sass_thread_inst_executed_op_hfma_pred_on_x4
derived__smsp__inst_executed_op_branch_pct
derived__smsp__sass_thread_inst_executed_op_dfma_pred_on_x2
derived__smsp__sass_thread_inst_executed_op_ffma_pred_on_x2
derived__smsp__sass_thread_inst_executed_op_hadd_pred_on_x2
derived__smsp__sass_thread_inst_executed_op_hfma_pred_on_x4
derived__smsp__sass_thread_inst_executed_op_hmul_pred_on_x2
derived_tempMetric0
derived_tempMetric1
derived_tempMetric2
derived_tempMetric3
derived_tempMetric4
derived_tempMetric5
device__attribute_architecture
device__attribute_async_engine_count
device__attribute_can_flush_remote_writes
device__attribute_can_map_host_memory
device__attribute_can_tex2d_gather
device__attribute_can_use_64_bit_stream_mem_ops
device__attribute_can_use_64_bit_stream_mem_ops_v1
device__attribute_can_use_host_pointer_for_registered_mem
device__attribute_can_use_stream_mem_ops_v1
device__attribute_can_use_stream_wait_value_nor
device__attribute_can_use_stream_wait_value_nor_v1
device__attribute_chip
device__attribute_clock_rate
device__attribute_cluster_launch
device__attribute_compute_capability_major
device__attribute_compute_capability_minor
device__attribute_compute_mode
device__attribute_compute_preemption_supported
device__attribute_concurrent_kernels
device__attribute_concurrent_managed_access
device__attribute_confidential_computing_mode
device__attribute_cooperative_launch
device__attribute_cooperative_multi_device_launch
device__attribute_deferred_mapping_cuda_array_supported
device__attribute_device_index
device__attribute_direct_managed_mem_access_from_host
device__attribute_display_name
device__attribute_dma_buf_supported
device__attribute_ecc_enabled
device__attribute_fb_bus_width
device__attribute_fbp_count
device__attribute_generic_compression_supported
device__attribute_global_l1_cache_supported
device__attribute_global_memory_bus_width
device__attribute_gpu_direct_rdma_flush_writes_options
device__attribute_gpu_direct_rdma_supported
device__attribute_gpu_direct_rdma_with_cuda_vmm_supported
device__attribute_gpu_direct_rdma_writes_ordering
device__attribute_gpu_overlap
device__attribute_gpu_pci_device_id
device__attribute_gpu_pci_ext_device_id
device__attribute_gpu_pci_ext_downstream_link_rate
device__attribute_gpu_pci_ext_downstream_link_width
device__attribute_gpu_pci_ext_gen
device__attribute_gpu_pci_ext_gpu_gen
device__attribute_gpu_pci_ext_gpu_link_rate
device__attribute_gpu_pci_ext_gpu_link_width
device__attribute_gpu_pci_revision_id
device__attribute_gpu_pci_sub_system_id
device__attribute_handle_type_fabric_supported
device__attribute_handle_type_posix_file_descriptor_supported
device__attribute_handle_type_win32_handle_supported
device__attribute_handle_type_win32_kmt_handle_supported
device__attribute_host_native_atomic_supported
device__attribute_host_numa_id
device__attribute_host_register_supported
device__attribute_implementation
device__attribute_integrated
device__attribute_ipc_event_supported
device__attribute_kernel_exec_timeout
device__attribute_l2_cache_size
device__attribute_l2s_count
device__attribute_limits_max_cta_per_sm
device__attribute_limits_num_tpcs
device__attribute_local_l1_cache_supported
device__attribute_managed_memory
device__attribute_max_access_policy_window_size
device__attribute_max_block_dim_x
device__attribute_max_block_dim_y
device__attribute_max_block_dim_z
device__attribute_max_blocks_per_multiprocessor
device__attribute_max_gpu_frequency_khz
device__attribute_max_grid_dim_x
device__attribute_max_grid_dim_y
device__attribute_max_grid_dim_z
device__attribute_max_ipc_per_multiprocessor
device__attribute_max_ipc_per_scheduler
device__attribute_max_mem_frequency_khz
device__attribute_max_persisting_l2_cache_size
device__attribute_max_pitch
device__attribute_max_registers_per_block
device__attribute_max_registers_per_multiprocessor
device__attribute_max_registers_per_thread
device__attribute_max_shared_memory_per_block
device__attribute_max_shared_memory_per_block_optin
device__attribute_max_shared_memory_per_multiprocessor
device__attribute_max_threads_per_block
device__attribute_max_threads_per_multiprocessor
device__attribute_max_warps_per_multiprocessor
device__attribute_max_warps_per_scheduler
device__attribute_maximum_surface1d_layered_layers
device__attribute_maximum_surface1d_layered_width
device__attribute_maximum_surface1d_width
device__attribute_maximum_surface2d_height
device__attribute_maximum_surface2d_layered_height
device__attribute_maximum_surface2d_layered_layers
device__attribute_maximum_surface2d_layered_width
device__attribute_maximum_surface2d_width
device__attribute_maximum_surface3d_depth
device__attribute_maximum_surface3d_height
device__attribute_maximum_surface3d_width
device__attribute_maximum_surfacecubemap_layered_layers
device__attribute_maximum_surfacecubemap_layered_width
device__attribute_maximum_surfacecubemap_width
device__attribute_maximum_texture1d_layered_layers
device__attribute_maximum_texture1d_layered_width
device__attribute_maximum_texture1d_linear_width
device__attribute_maximum_texture1d_mipmapped_width
device__attribute_maximum_texture1d_width
device__attribute_maximum_texture2d_gather_height
device__attribute_maximum_texture2d_gather_width
device__attribute_maximum_texture2d_height
device__attribute_maximum_texture2d_layered_height
device__attribute_maximum_texture2d_layered_layers
device__attribute_maximum_texture2d_layered_width
device__attribute_maximum_texture2d_linear_height
device__attribute_maximum_texture2d_linear_pitch
device__attribute_maximum_texture2d_linear_width
device__attribute_maximum_texture2d_mipmapped_height
device__attribute_maximum_texture2d_mipmapped_width
device__attribute_maximum_texture2d_width
device__attribute_maximum_texture3d_depth
device__attribute_maximum_texture3d_depth_alternate
device__attribute_maximum_texture3d_height
device__attribute_maximum_texture3d_height_alternate
device__attribute_maximum_texture3d_width
device__attribute_maximum_texture3d_width_alternate
device__attribute_maximum_texturecubemap_layered_layers
device__attribute_maximum_texturecubemap_layered_width
device__attribute_maximum_texturecubemap_width
device__attribute_mem_sync_domain_count
device__attribute_memory_clock_rate
device__attribute_memory_pools_supported
device__attribute_mempool_supported_handle_types
device__attribute_mps_enabled
device__attribute_multi_gpu_board
device__attribute_multi_gpu_board_group_id
device__attribute_multicast_supported
device__attribute_multiprocessor_count
device__attribute_num_l2s_per_fbp
device__attribute_num_schedulers_per_multiprocessor
device__attribute_num_tex_per_multiprocessor
device__attribute_numa_config
device__attribute_pageable_memory_access
device__attribute_pageable_memory_access_uses_host_page_tables
device__attribute_pci_bus_id
device__attribute_pci_device_id
device__attribute_pci_domain_id
device__attribute_ram_location
device__attribute_ram_type
device__attribute_reserved_shared_memory_per_block
device__attribute_sass_level
device__attribute_single_to_double_precision_perf_ratio
device__attribute_sparse_cuda_array_supported
device__attribute_stream_priorities_supported
device__attribute_surface_alignment
device__attribute_tcc_driver
device__attribute_tensor_map_access_supported
device__attribute_texture_alignment
device__attribute_texture_pitch_alignment
device__attribute_total_constant_memory
device__attribute_total_memory
device__attribute_unified_addressing
device__attribute_unified_function_pointers
device__attribute_virtual_address_management_supported
device__attribute_warp_size
dram__bytes.avg.peak_sustained
dram__bytes.avg.per_second
dram__bytes.max.peak_sustained
dram__bytes.max.per_second
dram__bytes.min.peak_sustained
dram__bytes.min.per_second
dram__bytes.sum.peak_sustained
dram__bytes.sum.per_second
dram__bytes_read.avg
dram__bytes_read.max
dram__bytes_read.min
dram__bytes_read.sum
dram__bytes_read.sum.pct_of_peak_sustained_elapsed
dram__bytes_read.sum.per_second
dram__bytes_write.avg
dram__bytes_write.max
dram__bytes_write.min
dram__bytes_write.sum
dram__bytes_write.sum.pct_of_peak_sustained_elapsed
dram__bytes_write.sum.per_second
dram__cycles_active.avg
dram__cycles_active.avg.pct_of_peak_sustained_elapsed
dram__cycles_active.max
dram__cycles_active.max.pct_of_peak_sustained_elapsed
dram__cycles_active.min
dram__cycles_active.min.pct_of_peak_sustained_elapsed
dram__cycles_active.sum
dram__cycles_active.sum.pct_of_peak_sustained_elapsed
dram__cycles_elapsed.avg
dram__cycles_elapsed.avg.per_second
dram__cycles_elapsed.max
dram__cycles_elapsed.max.per_second
dram__cycles_elapsed.min
dram__cycles_elapsed.min.per_second
dram__cycles_elapsed.sum
dram__cycles_elapsed.sum.per_second
dram__sectors_read.sum
dram__sectors_write.sum
fbpa__dram_sectors.avg.pct_of_peak_sustained_elapsed
fbpa__dram_sectors.max.pct_of_peak_sustained_elapsed
fbpa__dram_sectors.min.pct_of_peak_sustained_elapsed
fbpa__dram_sectors.sum.pct_of_peak_sustained_elapsed
gcc__average_cache_request_hit_rate.pct
gcc__cache_requests_type_constant.sum
gcc__cache_requests_type_constant.sum.pct_of_peak_sustained_elapsed
gcc__cache_requests_type_instruction.sum
gcc__cache_requests_type_instruction.sum.pct_of_peak_sustained_elapsed
gcc__xbar2gcc_sectors.sum
gcc__xbar2gcc_sectors.sum.pct_of_peak_sustained_elapsed
gpc__cycles_elapsed.avg
gpc__cycles_elapsed.avg.per_second
gpc__cycles_elapsed.max
gpc__cycles_elapsed.max.per_second
gpc__cycles_elapsed.min
gpc__cycles_elapsed.min.per_second
gpc__cycles_elapsed.sum
gpc__cycles_elapsed.sum.per_second
gpu__compute_memory_access_throughput.avg.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput_internal_activity.avg.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput_internal_activity.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput_internal_activity.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_access_throughput_internal_activity.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput.avg.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput_internal_activity.avg.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput_internal_activity.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput_internal_activity.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_request_throughput_internal_activity.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
gpu__time_duration.avg
gpu__time_duration.max
gpu__time_duration.min
gpu__time_duration.sum
idc__request_cycles_active.avg.pct_of_peak_sustained_elapsed
idc__request_cycles_active.max.pct_of_peak_sustained_elapsed
idc__request_cycles_active.min.pct_of_peak_sustained_elapsed
idc__request_cycles_active.sum.pct_of_peak_sustained_elapsed
idc__request_hit_rate.pct
idc__requests.sum
idc__requests.sum.pct_of_peak_sustained_elapsed
inst_executed
l1tex__cycles_active.avg
l1tex__cycles_active.max
l1tex__cycles_active.min
l1tex__cycles_active.sum
l1tex__cycles_elapsed.avg
l1tex__cycles_elapsed.avg.per_second
l1tex__cycles_elapsed.max
l1tex__cycles_elapsed.max.per_second
l1tex__cycles_elapsed.min
l1tex__cycles_elapsed.min.per_second
l1tex__cycles_elapsed.sum
l1tex__cycles_elapsed.sum.per_second
l1tex__data_bank_conflicts_pipe_lsu_mem_shared.sum
l1tex__data_bank_conflicts_pipe_lsu_mem_shared_op_atom.sum
l1tex__data_bank_conflicts_pipe_lsu_mem_shared_op_ld.sum
l1tex__data_bank_conflicts_pipe_lsu_mem_shared_op_st.sum
l1tex__data_bank_reads.avg.pct_of_peak_sustained_elapsed
l1tex__data_bank_reads.max.pct_of_peak_sustained_elapsed
l1tex__data_bank_reads.min.pct_of_peak_sustained_elapsed
l1tex__data_bank_reads.sum.pct_of_peak_sustained_elapsed
l1tex__data_bank_writes.avg.pct_of_peak_sustained_elapsed
l1tex__data_bank_writes.max.pct_of_peak_sustained_elapsed
l1tex__data_bank_writes.min.pct_of_peak_sustained_elapsed
l1tex__data_bank_writes.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts.avg.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts.max.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts.min.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts_mem_shared.sum
l1tex__data_pipe_lsu_wavefronts_mem_shared.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_atom.sum
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_ld.sum
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_ld.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_st.sum
l1tex__data_pipe_lsu_wavefronts_mem_shared_op_st.sum.pct_of_peak_sustained_elapsed
l1tex__data_pipe_tex_wavefronts.avg.pct_of_peak_sustained_elapsed
l1tex__data_pipe_tex_wavefronts.max.pct_of_peak_sustained_elapsed
l1tex__data_pipe_tex_wavefronts.min.pct_of_peak_sustained_elapsed
l1tex__data_pipe_tex_wavefronts.sum.pct_of_peak_sustained_elapsed
l1tex__f_wavefronts.avg.pct_of_peak_sustained_elapsed
l1tex__f_wavefronts.max.pct_of_peak_sustained_elapsed
l1tex__f_wavefronts.min.pct_of_peak_sustained_elapsed
l1tex__f_wavefronts.sum.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active.avg.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active.max.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active.min.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active.sum.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active_mem_lg.avg.peak_sustained
l1tex__lsu_writeback_active_mem_lg.avg.per_second
l1tex__lsu_writeback_active_mem_lg.max.peak_sustained
l1tex__lsu_writeback_active_mem_lg.max.per_second
l1tex__lsu_writeback_active_mem_lg.min.peak_sustained
l1tex__lsu_writeback_active_mem_lg.min.per_second
l1tex__lsu_writeback_active_mem_lg.sum
l1tex__lsu_writeback_active_mem_lg.sum.pct_of_peak_sustained_elapsed
l1tex__lsu_writeback_active_mem_lg.sum.peak_sustained
l1tex__lsu_writeback_active_mem_lg.sum.per_second
l1tex__lsuin_requests.avg.pct_of_peak_sustained_elapsed
l1tex__lsuin_requests.max.pct_of_peak_sustained_elapsed
l1tex__lsuin_requests.min.pct_of_peak_sustained_elapsed
l1tex__lsuin_requests.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_req_cycles_active.avg.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_req_cycles_active.max.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_req_cycles_active.min.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_req_cycles_active.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_bytes.sum
l1tex__m_l1tex2xbar_write_bytes.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_bytes.sum.per_second
l1tex__m_l1tex2xbar_write_sectors_mem_global_op_atom.sum
l1tex__m_l1tex2xbar_write_sectors_mem_global_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_sectors_mem_global_op_red.sum
l1tex__m_l1tex2xbar_write_sectors_mem_global_op_red.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_sectors_mem_lg_op_st.sum
l1tex__m_l1tex2xbar_write_sectors_mem_lg_op_st.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_atom.sum
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_red.sum
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_red.sum.pct_of_peak_sustained_elapsed
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_st.sum
l1tex__m_l1tex2xbar_write_sectors_mem_surface_op_st.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_bytes.sum
l1tex__m_xbar2l1tex_read_bytes.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_bytes.sum.per_second
l1tex__m_xbar2l1tex_read_sectors.avg.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors.max.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors.min.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors_mem_global_op_atom.sum
l1tex__m_xbar2l1tex_read_sectors_mem_global_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors_mem_lg_op_ld.sum
l1tex__m_xbar2l1tex_read_sectors_mem_lg_op_ld.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors_mem_surface_op_atom.sum
l1tex__m_xbar2l1tex_read_sectors_mem_surface_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors_mem_surface_op_ld.sum
l1tex__m_xbar2l1tex_read_sectors_mem_surface_op_ld.sum.pct_of_peak_sustained_elapsed
l1tex__m_xbar2l1tex_read_sectors_mem_texture.sum
l1tex__m_xbar2l1tex_read_sectors_mem_texture.sum.pct_of_peak_sustained_elapsed
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_atom.sum
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_atom.sum.pct_of_peak_sustained_elapsed
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_ld.sum
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_ld.sum.pct_of_peak_sustained_elapsed
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_red.sum
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_red.sum.pct_of_peak_sustained_elapsed
l1tex__t_output_wavefronts_pipe_lsu_mem_global_op_st.sum